# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFormTabs.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(456, 549)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/scLogolARGE.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("qproperty-alignment: AlignCenter;"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_14.addWidget(self.label)
        self.btnReset = QtGui.QPushButton(self.centralwidget)
        self.btnReset.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.btnReset.setFont(font)
        self.btnReset.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.horizontalLayout_14.addWidget(self.btnReset)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.btnConversions = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnConversions.setFont(font)
        self.btnConversions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnConversions.setTabPosition(QtGui.QTabWidget.North)
        self.btnConversions.setTabShape(QtGui.QTabWidget.Rounded)
        self.btnConversions.setElideMode(QtCore.Qt.ElideNone)
        self.btnConversions.setObjectName(_fromUtf8("btnConversions"))
        self.tabUnitConversion = QtGui.QWidget()
        self.tabUnitConversion.setObjectName(_fromUtf8("tabUnitConversion"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabUnitConversion)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelTitleConversion = QtGui.QLabel(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitleConversion.setFont(font)
        self.labelTitleConversion.setStyleSheet(_fromUtf8("qproperty-alignment: AlignCenter;"))
        self.labelTitleConversion.setObjectName(_fromUtf8("labelTitleConversion"))
        self.horizontalLayout_2.addWidget(self.labelTitleConversion)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelTitleTo = QtGui.QLabel(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelTitleTo.setFont(font)
        self.labelTitleTo.setStyleSheet(_fromUtf8("qproperty-alignment: AlignCenter;"))
        self.labelTitleTo.setObjectName(_fromUtf8("labelTitleTo"))
        self.gridLayout.addWidget(self.labelTitleTo, 0, 2, 1, 1)
        self.labelTitleFrom = QtGui.QLabel(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelTitleFrom.setFont(font)
        self.labelTitleFrom.setStyleSheet(_fromUtf8("qproperty-alignment: AlignCenter;"))
        self.labelTitleFrom.setObjectName(_fromUtf8("labelTitleFrom"))
        self.gridLayout.addWidget(self.labelTitleFrom, 0, 1, 1, 1)
        self.lineEditOutputVolume = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.lineEditOutputVolume.setFont(font)
        self.lineEditOutputVolume.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.lineEditOutputVolume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditOutputVolume.setReadOnly(True)
        self.lineEditOutputVolume.setObjectName(_fromUtf8("lineEditOutputVolume"))
        self.gridLayout.addWidget(self.lineEditOutputVolume, 6, 3, 1, 1)
        self.labelTitleVolume = QtGui.QLabel(self.tabUnitConversion)
        self.labelTitleVolume.setObjectName(_fromUtf8("labelTitleVolume"))
        self.gridLayout.addWidget(self.labelTitleVolume, 5, 0, 2, 1)
        self.label_3 = QtGui.QLabel(self.tabUnitConversion)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 7, 0, 2, 1)
        self.lineEditInputMassFlow = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditInputMassFlow.setFont(font)
        self.lineEditInputMassFlow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditInputMassFlow.setObjectName(_fromUtf8("lineEditInputMassFlow"))
        self.gridLayout.addWidget(self.lineEditInputMassFlow, 11, 3, 1, 1)
        self.lineEditOutputArea = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.lineEditOutputArea.setFont(font)
        self.lineEditOutputArea.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.lineEditOutputArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditOutputArea.setReadOnly(True)
        self.lineEditOutputArea.setObjectName(_fromUtf8("lineEditOutputArea"))
        self.gridLayout.addWidget(self.lineEditOutputArea, 4, 3, 1, 1)
        self.lineEditOutputLength = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.lineEditOutputLength.setFont(font)
        self.lineEditOutputLength.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.lineEditOutputLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditOutputLength.setReadOnly(True)
        self.lineEditOutputLength.setObjectName(_fromUtf8("lineEditOutputLength"))
        self.gridLayout.addWidget(self.lineEditOutputLength, 2, 3, 1, 1)
        self.lineEditInputArea = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditInputArea.setFont(font)
        self.lineEditInputArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditInputArea.setObjectName(_fromUtf8("lineEditInputArea"))
        self.gridLayout.addWidget(self.lineEditInputArea, 3, 3, 1, 1)
        self.lineEditOutputMassFlow = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.lineEditOutputMassFlow.setFont(font)
        self.lineEditOutputMassFlow.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.lineEditOutputMassFlow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditOutputMassFlow.setReadOnly(True)
        self.lineEditOutputMassFlow.setObjectName(_fromUtf8("lineEditOutputMassFlow"))
        self.gridLayout.addWidget(self.lineEditOutputMassFlow, 12, 3, 1, 1)
        self.lineEditInputDensity = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditInputDensity.setFont(font)
        self.lineEditInputDensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditInputDensity.setObjectName(_fromUtf8("lineEditInputDensity"))
        self.gridLayout.addWidget(self.lineEditInputDensity, 9, 3, 1, 1)
        self.lineEditOutputDensity = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.lineEditOutputDensity.setFont(font)
        self.lineEditOutputDensity.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.lineEditOutputDensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditOutputDensity.setReadOnly(True)
        self.lineEditOutputDensity.setObjectName(_fromUtf8("lineEditOutputDensity"))
        self.gridLayout.addWidget(self.lineEditOutputDensity, 10, 3, 1, 1)
        self.lineEditInputVolume = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditInputVolume.setFont(font)
        self.lineEditInputVolume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditInputVolume.setObjectName(_fromUtf8("lineEditInputVolume"))
        self.gridLayout.addWidget(self.lineEditInputVolume, 5, 3, 1, 1)
        self.lineEditInputMass = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditInputMass.setFont(font)
        self.lineEditInputMass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditInputMass.setObjectName(_fromUtf8("lineEditInputMass"))
        self.gridLayout.addWidget(self.lineEditInputMass, 7, 3, 1, 1)
        self.labelTitleVelocity = QtGui.QLabel(self.tabUnitConversion)
        self.labelTitleVelocity.setObjectName(_fromUtf8("labelTitleVelocity"))
        self.gridLayout.addWidget(self.labelTitleVelocity, 11, 0, 2, 1)
        self.label_4 = QtGui.QLabel(self.tabUnitConversion)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 9, 0, 2, 1)
        self.labelTitleLength = QtGui.QLabel(self.tabUnitConversion)
        self.labelTitleLength.setObjectName(_fromUtf8("labelTitleLength"))
        self.gridLayout.addWidget(self.labelTitleLength, 1, 0, 2, 1)
        self.labelTitleArea = QtGui.QLabel(self.tabUnitConversion)
        self.labelTitleArea.setObjectName(_fromUtf8("labelTitleArea"))
        self.gridLayout.addWidget(self.labelTitleArea, 3, 0, 2, 1)
        self.lineEditOutputMass = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.lineEditOutputMass.setFont(font)
        self.lineEditOutputMass.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.lineEditOutputMass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditOutputMass.setReadOnly(True)
        self.lineEditOutputMass.setObjectName(_fromUtf8("lineEditOutputMass"))
        self.gridLayout.addWidget(self.lineEditOutputMass, 8, 3, 1, 1)
        self.lineEditInputLength = QtGui.QLineEdit(self.tabUnitConversion)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditInputLength.setFont(font)
        self.lineEditInputLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditInputLength.setObjectName(_fromUtf8("lineEditInputLength"))
        self.gridLayout.addWidget(self.lineEditInputLength, 1, 3, 1, 1)
        self.comboBoxFromLength = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxFromLength.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxFromLength.setFont(font)
        self.comboBoxFromLength.setObjectName(_fromUtf8("comboBoxFromLength"))
        self.comboBoxFromLength.addItem(_fromUtf8(""))
        self.comboBoxFromLength.addItem(_fromUtf8(""))
        self.comboBoxFromLength.addItem(_fromUtf8(""))
        self.comboBoxFromLength.addItem(_fromUtf8(""))
        self.comboBoxFromLength.addItem(_fromUtf8(""))
        self.comboBoxFromLength.addItem(_fromUtf8(""))
        self.comboBoxFromLength.addItem(_fromUtf8(""))
        self.comboBoxFromLength.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxFromLength, 1, 1, 2, 1)
        self.comboBoxToLength = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxToLength.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxToLength.setFont(font)
        self.comboBoxToLength.setObjectName(_fromUtf8("comboBoxToLength"))
        self.comboBoxToLength.addItem(_fromUtf8(""))
        self.comboBoxToLength.addItem(_fromUtf8(""))
        self.comboBoxToLength.addItem(_fromUtf8(""))
        self.comboBoxToLength.addItem(_fromUtf8(""))
        self.comboBoxToLength.addItem(_fromUtf8(""))
        self.comboBoxToLength.addItem(_fromUtf8(""))
        self.comboBoxToLength.addItem(_fromUtf8(""))
        self.comboBoxToLength.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxToLength, 1, 2, 2, 1)
        self.comboBoxFromArea = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxFromArea.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxFromArea.setFont(font)
        self.comboBoxFromArea.setObjectName(_fromUtf8("comboBoxFromArea"))
        self.comboBoxFromArea.addItem(_fromUtf8(""))
        self.comboBoxFromArea.addItem(_fromUtf8(""))
        self.comboBoxFromArea.addItem(_fromUtf8(""))
        self.comboBoxFromArea.addItem(_fromUtf8(""))
        self.comboBoxFromArea.addItem(_fromUtf8(""))
        self.comboBoxFromArea.addItem(_fromUtf8(""))
        self.comboBoxFromArea.addItem(_fromUtf8(""))
        self.comboBoxFromArea.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxFromArea, 3, 1, 2, 1)
        self.comboBoxToLength_2 = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxToLength_2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxToLength_2.setFont(font)
        self.comboBoxToLength_2.setObjectName(_fromUtf8("comboBoxToLength_2"))
        self.comboBoxToLength_2.addItem(_fromUtf8(""))
        self.comboBoxToLength_2.addItem(_fromUtf8(""))
        self.comboBoxToLength_2.addItem(_fromUtf8(""))
        self.comboBoxToLength_2.addItem(_fromUtf8(""))
        self.comboBoxToLength_2.addItem(_fromUtf8(""))
        self.comboBoxToLength_2.addItem(_fromUtf8(""))
        self.comboBoxToLength_2.addItem(_fromUtf8(""))
        self.comboBoxToLength_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxToLength_2, 3, 2, 2, 1)
        self.comboBoxFromVolume = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxFromVolume.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxFromVolume.setFont(font)
        self.comboBoxFromVolume.setObjectName(_fromUtf8("comboBoxFromVolume"))
        self.comboBoxFromVolume.addItem(_fromUtf8(""))
        self.comboBoxFromVolume.addItem(_fromUtf8(""))
        self.comboBoxFromVolume.addItem(_fromUtf8(""))
        self.comboBoxFromVolume.addItem(_fromUtf8(""))
        self.comboBoxFromVolume.addItem(_fromUtf8(""))
        self.comboBoxFromVolume.addItem(_fromUtf8(""))
        self.comboBoxFromVolume.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxFromVolume, 5, 1, 2, 1)
        self.comboBoxToVolume = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxToVolume.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxToVolume.setFont(font)
        self.comboBoxToVolume.setObjectName(_fromUtf8("comboBoxToVolume"))
        self.comboBoxToVolume.addItem(_fromUtf8(""))
        self.comboBoxToVolume.addItem(_fromUtf8(""))
        self.comboBoxToVolume.addItem(_fromUtf8(""))
        self.comboBoxToVolume.addItem(_fromUtf8(""))
        self.comboBoxToVolume.addItem(_fromUtf8(""))
        self.comboBoxToVolume.addItem(_fromUtf8(""))
        self.comboBoxToVolume.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxToVolume, 5, 2, 2, 1)
        self.comboBoxFromMass = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxFromMass.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxFromMass.setFont(font)
        self.comboBoxFromMass.setObjectName(_fromUtf8("comboBoxFromMass"))
        self.comboBoxFromMass.addItem(_fromUtf8(""))
        self.comboBoxFromMass.addItem(_fromUtf8(""))
        self.comboBoxFromMass.addItem(_fromUtf8(""))
        self.comboBoxFromMass.addItem(_fromUtf8(""))
        self.comboBoxFromMass.addItem(_fromUtf8(""))
        self.comboBoxFromMass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxFromMass, 7, 1, 2, 1)
        self.comboBoxToMass = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxToMass.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxToMass.setFont(font)
        self.comboBoxToMass.setObjectName(_fromUtf8("comboBoxToMass"))
        self.comboBoxToMass.addItem(_fromUtf8(""))
        self.comboBoxToMass.addItem(_fromUtf8(""))
        self.comboBoxToMass.addItem(_fromUtf8(""))
        self.comboBoxToMass.addItem(_fromUtf8(""))
        self.comboBoxToMass.addItem(_fromUtf8(""))
        self.comboBoxToMass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxToMass, 7, 2, 2, 1)
        self.comboBoxFromDensity = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxFromDensity.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxFromDensity.setFont(font)
        self.comboBoxFromDensity.setObjectName(_fromUtf8("comboBoxFromDensity"))
        self.comboBoxFromDensity.addItem(_fromUtf8(""))
        self.comboBoxFromDensity.addItem(_fromUtf8(""))
        self.comboBoxFromDensity.addItem(_fromUtf8(""))
        self.comboBoxFromDensity.addItem(_fromUtf8(""))
        self.comboBoxFromDensity.addItem(_fromUtf8(""))
        self.comboBoxFromDensity.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxFromDensity, 9, 1, 2, 1)
        self.comboBoxToDensity = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxToDensity.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxToDensity.setFont(font)
        self.comboBoxToDensity.setObjectName(_fromUtf8("comboBoxToDensity"))
        self.comboBoxToDensity.addItem(_fromUtf8(""))
        self.comboBoxToDensity.addItem(_fromUtf8(""))
        self.comboBoxToDensity.addItem(_fromUtf8(""))
        self.comboBoxToDensity.addItem(_fromUtf8(""))
        self.comboBoxToDensity.addItem(_fromUtf8(""))
        self.comboBoxToDensity.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxToDensity, 9, 2, 2, 1)
        self.comboBoxFromMassFlow = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxFromMassFlow.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxFromMassFlow.setFont(font)
        self.comboBoxFromMassFlow.setObjectName(_fromUtf8("comboBoxFromMassFlow"))
        self.comboBoxFromMassFlow.addItem(_fromUtf8(""))
        self.comboBoxFromMassFlow.addItem(_fromUtf8(""))
        self.comboBoxFromMassFlow.addItem(_fromUtf8(""))
        self.comboBoxFromMassFlow.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxFromMassFlow, 11, 1, 2, 1)
        self.comboBoxToMassFlow = QtGui.QComboBox(self.tabUnitConversion)
        self.comboBoxToMassFlow.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBoxToMassFlow.setFont(font)
        self.comboBoxToMassFlow.setObjectName(_fromUtf8("comboBoxToMassFlow"))
        self.comboBoxToMassFlow.addItem(_fromUtf8(""))
        self.comboBoxToMassFlow.addItem(_fromUtf8(""))
        self.comboBoxToMassFlow.addItem(_fromUtf8(""))
        self.comboBoxToMassFlow.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxToMassFlow, 11, 2, 2, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.btnConvert = QtGui.QPushButton(self.tabUnitConversion)
        self.btnConvert.setMinimumSize(QtCore.QSize(200, 0))
        self.btnConvert.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnConvert.setFont(font)
        self.btnConvert.setObjectName(_fromUtf8("btnConvert"))
        self.horizontalLayout_13.addWidget(self.btnConvert)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.btnConversions.addTab(self.tabUnitConversion, _fromUtf8(""))
        self.tabCircles = QtGui.QWidget()
        self.tabCircles.setObjectName(_fromUtf8("tabCircles"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabCircles)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labelCircleTitle = QtGui.QLabel(self.tabCircles)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.labelCircleTitle.setFont(font)
        self.labelCircleTitle.setStyleSheet(_fromUtf8("qproperty-alignment: AlignCenter;"))
        self.labelCircleTitle.setObjectName(_fromUtf8("labelCircleTitle"))
        self.verticalLayout_3.addWidget(self.labelCircleTitle)
        self.labelInputCircle = QtGui.QLabel(self.tabCircles)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelInputCircle.setFont(font)
        self.labelInputCircle.setObjectName(_fromUtf8("labelInputCircle"))
        self.verticalLayout_3.addWidget(self.labelInputCircle)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelDiameter = QtGui.QLabel(self.tabCircles)
        self.labelDiameter.setMinimumSize(QtCore.QSize(250, 0))
        self.labelDiameter.setObjectName(_fromUtf8("labelDiameter"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelDiameter)
        self.txtCLS_Diamter = QtGui.QLineEdit(self.tabCircles)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtCLS_Diamter.setFont(font)
        self.txtCLS_Diamter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtCLS_Diamter.setObjectName(_fromUtf8("txtCLS_Diamter"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtCLS_Diamter)
        self.labelArea = QtGui.QLabel(self.tabCircles)
        self.labelArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelArea.setObjectName(_fromUtf8("labelArea"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelArea)
        self.txtCLS_Area = QtGui.QLineEdit(self.tabCircles)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtCLS_Area.setFont(font)
        self.txtCLS_Area.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtCLS_Area.setObjectName(_fromUtf8("txtCLS_Area"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtCLS_Area)
        self.labelCircumference = QtGui.QLabel(self.tabCircles)
        self.labelCircumference.setObjectName(_fromUtf8("labelCircumference"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelCircumference)
        self.txtCLS_Circumference = QtGui.QLineEdit(self.tabCircles)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtCLS_Circumference.setFont(font)
        self.txtCLS_Circumference.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtCLS_Circumference.setObjectName(_fromUtf8("txtCLS_Circumference"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtCLS_Circumference)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.btnCircles = QtGui.QPushButton(self.tabCircles)
        self.btnCircles.setMinimumSize(QtCore.QSize(200, 0))
        self.btnCircles.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnCircles.setFont(font)
        self.btnCircles.setObjectName(_fromUtf8("btnCircles"))
        self.horizontalLayout_11.addWidget(self.btnCircles)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.imageCircle = QtGui.QLabel(self.tabCircles)
        self.imageCircle.setMaximumSize(QtCore.QSize(345, 124))
        self.imageCircle.setText(_fromUtf8(""))
        self.imageCircle.setPixmap(QtGui.QPixmap(_fromUtf8("images/image_circle.png")))
        self.imageCircle.setScaledContents(True)
        self.imageCircle.setObjectName(_fromUtf8("imageCircle"))
        self.horizontalLayout_12.addWidget(self.imageCircle)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.btnConversions.addTab(self.tabCircles, _fromUtf8(""))
        self.tabTaper = QtGui.QWidget()
        self.tabTaper.setObjectName(_fromUtf8("tabTaper"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabTaper)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelTaperTitle = QtGui.QLabel(self.tabTaper)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTaperTitle.setFont(font)
        self.labelTaperTitle.setStyleSheet(_fromUtf8("qproperty-alignment: AlignCenter;"))
        self.labelTaperTitle.setObjectName(_fromUtf8("labelTaperTitle"))
        self.verticalLayout_2.addWidget(self.labelTaperTitle)
        self.labelTaperInput = QtGui.QLabel(self.tabTaper)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelTaperInput.setFont(font)
        self.labelTaperInput.setObjectName(_fromUtf8("labelTaperInput"))
        self.verticalLayout_2.addWidget(self.labelTaperInput)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelAngle = QtGui.QLabel(self.tabTaper)
        self.labelAngle.setMinimumSize(QtCore.QSize(250, 0))
        self.labelAngle.setObjectName(_fromUtf8("labelAngle"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelAngle)
        self.labelDiameter1 = QtGui.QLabel(self.tabTaper)
        self.labelDiameter1.setObjectName(_fromUtf8("labelDiameter1"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelDiameter1)
        self.labelDiameter2 = QtGui.QLabel(self.tabTaper)
        self.labelDiameter2.setObjectName(_fromUtf8("labelDiameter2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelDiameter2)
        self.labelLength = QtGui.QLabel(self.tabTaper)
        self.labelLength.setObjectName(_fromUtf8("labelLength"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelLength)
        self.txtTA_Angle = QtGui.QLineEdit(self.tabTaper)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtTA_Angle.setFont(font)
        self.txtTA_Angle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtTA_Angle.setObjectName(_fromUtf8("txtTA_Angle"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtTA_Angle)
        self.txtTA_Diameter1 = QtGui.QLineEdit(self.tabTaper)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtTA_Diameter1.setFont(font)
        self.txtTA_Diameter1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtTA_Diameter1.setObjectName(_fromUtf8("txtTA_Diameter1"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtTA_Diameter1)
        self.txtTA_Diameter2 = QtGui.QLineEdit(self.tabTaper)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtTA_Diameter2.setFont(font)
        self.txtTA_Diameter2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtTA_Diameter2.setObjectName(_fromUtf8("txtTA_Diameter2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtTA_Diameter2)
        self.txtTA_Length = QtGui.QLineEdit(self.tabTaper)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtTA_Length.setFont(font)
        self.txtTA_Length.setStyleSheet(_fromUtf8(""))
        self.txtTA_Length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtTA_Length.setReadOnly(False)
        self.txtTA_Length.setObjectName(_fromUtf8("txtTA_Length"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtTA_Length)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.btnTaper = QtGui.QPushButton(self.tabTaper)
        self.btnTaper.setMinimumSize(QtCore.QSize(200, 0))
        self.btnTaper.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnTaper.setFont(font)
        self.btnTaper.setObjectName(_fromUtf8("btnTaper"))
        self.horizontalLayout_9.addWidget(self.btnTaper)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.imageTaper = QtGui.QLabel(self.tabTaper)
        self.imageTaper.setMaximumSize(QtCore.QSize(352, 194))
        self.imageTaper.setText(_fromUtf8(""))
        self.imageTaper.setPixmap(QtGui.QPixmap(_fromUtf8("images/image_taper.png")))
        self.imageTaper.setScaledContents(True)
        self.imageTaper.setObjectName(_fromUtf8("imageTaper"))
        self.horizontalLayout_10.addWidget(self.imageTaper)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.btnConversions.addTab(self.tabTaper, _fromUtf8(""))
        self.tabRaceTrack = QtGui.QWidget()
        self.tabRaceTrack.setObjectName(_fromUtf8("tabRaceTrack"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabRaceTrack)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelTitleRT = QtGui.QLabel(self.tabRaceTrack)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitleRT.setFont(font)
        self.labelTitleRT.setStyleSheet(_fromUtf8("qproperty-alignment: AlignCenter;"))
        self.labelTitleRT.setObjectName(_fromUtf8("labelTitleRT"))
        self.verticalLayout_4.addWidget(self.labelTitleRT)
        self.labelInputRT = QtGui.QLabel(self.tabRaceTrack)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelInputRT.setFont(font)
        self.labelInputRT.setObjectName(_fromUtf8("labelInputRT"))
        self.verticalLayout_4.addWidget(self.labelInputRT)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelRTx = QtGui.QLabel(self.tabRaceTrack)
        self.labelRTx.setMinimumSize(QtCore.QSize(250, 0))
        self.labelRTx.setObjectName(_fromUtf8("labelRTx"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelRTx)
        self.labelRTy = QtGui.QLabel(self.tabRaceTrack)
        self.labelRTy.setObjectName(_fromUtf8("labelRTy"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelRTy)
        self.labelRTarea = QtGui.QLabel(self.tabRaceTrack)
        self.labelRTarea.setObjectName(_fromUtf8("labelRTarea"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelRTarea)
        self.labelRTcircumference = QtGui.QLabel(self.tabRaceTrack)
        self.labelRTcircumference.setObjectName(_fromUtf8("labelRTcircumference"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelRTcircumference)
        self.txtRTRK_x = QtGui.QLineEdit(self.tabRaceTrack)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtRTRK_x.setFont(font)
        self.txtRTRK_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRTRK_x.setObjectName(_fromUtf8("txtRTRK_x"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtRTRK_x)
        self.txtRTRK_csa = QtGui.QLineEdit(self.tabRaceTrack)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.txtRTRK_csa.setFont(font)
        self.txtRTRK_csa.setStyleSheet(_fromUtf8(""))
        self.txtRTRK_csa.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRTRK_csa.setReadOnly(False)
        self.txtRTRK_csa.setObjectName(_fromUtf8("txtRTRK_csa"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtRTRK_csa)
        self.txtRTRK_cfm = QtGui.QLineEdit(self.tabRaceTrack)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.txtRTRK_cfm.setFont(font)
        self.txtRTRK_cfm.setStyleSheet(_fromUtf8(""))
        self.txtRTRK_cfm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRTRK_cfm.setReadOnly(False)
        self.txtRTRK_cfm.setObjectName(_fromUtf8("txtRTRK_cfm"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtRTRK_cfm)
        self.txtRTRK_y = QtGui.QLineEdit(self.tabRaceTrack)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtRTRK_y.setFont(font)
        self.txtRTRK_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRTRK_y.setObjectName(_fromUtf8("txtRTRK_y"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtRTRK_y)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.btnRacetrack = QtGui.QPushButton(self.tabRaceTrack)
        self.btnRacetrack.setMinimumSize(QtCore.QSize(200, 0))
        self.btnRacetrack.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnRacetrack.setFont(font)
        self.btnRacetrack.setObjectName(_fromUtf8("btnRacetrack"))
        self.horizontalLayout_5.addWidget(self.btnRacetrack)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.imageRacetrack = QtGui.QLabel(self.tabRaceTrack)
        self.imageRacetrack.setMaximumSize(QtCore.QSize(400, 139))
        self.imageRacetrack.setText(_fromUtf8(""))
        self.imageRacetrack.setPixmap(QtGui.QPixmap(_fromUtf8("images/image_racetrack.png")))
        self.imageRacetrack.setScaledContents(True)
        self.imageRacetrack.setObjectName(_fromUtf8("imageRacetrack"))
        self.horizontalLayout_6.addWidget(self.imageRacetrack)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.btnConversions.addTab(self.tabRaceTrack, _fromUtf8(""))
        self.tabElipse = QtGui.QWidget()
        self.tabElipse.setObjectName(_fromUtf8("tabElipse"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabElipse)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelTitleElipse = QtGui.QLabel(self.tabElipse)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitleElipse.setFont(font)
        self.labelTitleElipse.setStyleSheet(_fromUtf8("qproperty-alignment: AlignCenter;"))
        self.labelTitleElipse.setObjectName(_fromUtf8("labelTitleElipse"))
        self.verticalLayout_5.addWidget(self.labelTitleElipse)
        self.labelInputElipse = QtGui.QLabel(self.tabElipse)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelInputElipse.setFont(font)
        self.labelInputElipse.setObjectName(_fromUtf8("labelInputElipse"))
        self.verticalLayout_5.addWidget(self.labelInputElipse)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelSMajor = QtGui.QLabel(self.tabElipse)
        self.labelSMajor.setMinimumSize(QtCore.QSize(250, 0))
        self.labelSMajor.setObjectName(_fromUtf8("labelSMajor"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelSMajor)
        self.labelSMinor = QtGui.QLabel(self.tabElipse)
        self.labelSMinor.setObjectName(_fromUtf8("labelSMinor"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelSMinor)
        self.labelEArea = QtGui.QLabel(self.tabElipse)
        self.labelEArea.setObjectName(_fromUtf8("labelEArea"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelEArea)
        self.labelEcircumference = QtGui.QLabel(self.tabElipse)
        self.labelEcircumference.setObjectName(_fromUtf8("labelEcircumference"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelEcircumference)
        self.txtElipses_semimajor = QtGui.QLineEdit(self.tabElipse)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtElipses_semimajor.setFont(font)
        self.txtElipses_semimajor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtElipses_semimajor.setObjectName(_fromUtf8("txtElipses_semimajor"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtElipses_semimajor)
        self.txtElipses_semiminor = QtGui.QLineEdit(self.tabElipse)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtElipses_semiminor.setFont(font)
        self.txtElipses_semiminor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtElipses_semiminor.setObjectName(_fromUtf8("txtElipses_semiminor"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtElipses_semiminor)
        self.txtElipses_csa = QtGui.QLineEdit(self.tabElipse)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.txtElipses_csa.setFont(font)
        self.txtElipses_csa.setStyleSheet(_fromUtf8(""))
        self.txtElipses_csa.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtElipses_csa.setReadOnly(False)
        self.txtElipses_csa.setObjectName(_fromUtf8("txtElipses_csa"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtElipses_csa)
        self.txtElipses_circumference = QtGui.QLineEdit(self.tabElipse)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.txtElipses_circumference.setFont(font)
        self.txtElipses_circumference.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.txtElipses_circumference.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtElipses_circumference.setReadOnly(True)
        self.txtElipses_circumference.setObjectName(_fromUtf8("txtElipses_circumference"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtElipses_circumference)
        self.verticalLayout_5.addLayout(self.formLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.btnElipses = QtGui.QPushButton(self.tabElipse)
        self.btnElipses.setMinimumSize(QtCore.QSize(200, 0))
        self.btnElipses.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnElipses.setObjectName(_fromUtf8("btnElipses"))
        self.horizontalLayout_3.addWidget(self.btnElipses)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.imageElipse = QtGui.QLabel(self.tabElipse)
        self.imageElipse.setMaximumSize(QtCore.QSize(329, 204))
        self.imageElipse.setText(_fromUtf8(""))
        self.imageElipse.setPixmap(QtGui.QPixmap(_fromUtf8("images/image_elipse.png")))
        self.imageElipse.setScaledContents(True)
        self.imageElipse.setObjectName(_fromUtf8("imageElipse"))
        self.horizontalLayout_4.addWidget(self.imageElipse)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)
        self.btnConversions.addTab(self.tabElipse, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_7.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setMinimumSize(QtCore.QSize(250, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.txtRectangleR = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtRectangleR.setFont(font)
        self.txtRectangleR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRectangleR.setObjectName(_fromUtf8("txtRectangleR"))
        self.gridLayout_2.addWidget(self.txtRectangleR, 2, 1, 1, 1)
        self.txtRectangleCfm = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.txtRectangleCfm.setFont(font)
        self.txtRectangleCfm.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.txtRectangleCfm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRectangleCfm.setReadOnly(True)
        self.txtRectangleCfm.setObjectName(_fromUtf8("txtRectangleCfm"))
        self.gridLayout_2.addWidget(self.txtRectangleCfm, 4, 1, 1, 1)
        self.txtRectangleY = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtRectangleY.setFont(font)
        self.txtRectangleY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRectangleY.setObjectName(_fromUtf8("txtRectangleY"))
        self.gridLayout_2.addWidget(self.txtRectangleY, 1, 1, 1, 1)
        self.txtRectangleX = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtRectangleX.setFont(font)
        self.txtRectangleX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRectangleX.setObjectName(_fromUtf8("txtRectangleX"))
        self.gridLayout_2.addWidget(self.txtRectangleX, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.txtRectangleArea = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.txtRectangleArea.setFont(font)
        self.txtRectangleArea.setStyleSheet(_fromUtf8("background: rgb(229, 229, 229)"))
        self.txtRectangleArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRectangleArea.setReadOnly(True)
        self.txtRectangleArea.setObjectName(_fromUtf8("txtRectangleArea"))
        self.gridLayout_2.addWidget(self.txtRectangleArea, 3, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.btnRectangle = QtGui.QPushButton(self.tab)
        self.btnRectangle.setMinimumSize(QtCore.QSize(200, 0))
        self.btnRectangle.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnRectangle.setObjectName(_fromUtf8("btnRectangle"))
        self.horizontalLayout_7.addWidget(self.btnRectangle)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.imageRectangle = QtGui.QLabel(self.tab)
        self.imageRectangle.setMaximumSize(QtCore.QSize(393, 132))
        self.imageRectangle.setText(_fromUtf8(""))
        self.imageRectangle.setPixmap(QtGui.QPixmap(_fromUtf8("images/image_rectangle.png")))
        self.imageRectangle.setScaledContents(True)
        self.imageRectangle.setObjectName(_fromUtf8("imageRectangle"))
        self.horizontalLayout_8.addWidget(self.imageRectangle)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem21)
        self.btnConversions.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.btnConversions)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 456, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExit = QtGui.QMenu(self.menubar)
        self.menuExit.setObjectName(_fromUtf8("menuExit"))
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/sCexit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionExit)
        self.menuExit.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        self.btnConversions.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Shape Calculator", None))
        self.label.setText(_translate("MainWindow", "Shape Calculator", None))
        self.btnReset.setText(_translate("MainWindow", "Clear Form Fields", None))
        self.labelTitleConversion.setText(_translate("MainWindow", "Conversion Units", None))
        self.labelTitleTo.setText(_translate("MainWindow", "To", None))
        self.labelTitleFrom.setText(_translate("MainWindow", "From", None))
        self.lineEditOutputVolume.setText(_translate("MainWindow", "0", None))
        self.labelTitleVolume.setText(_translate("MainWindow", "Volume", None))
        self.label_3.setText(_translate("MainWindow", "Mass", None))
        self.lineEditInputMassFlow.setText(_translate("MainWindow", "0", None))
        self.lineEditOutputArea.setText(_translate("MainWindow", "0", None))
        self.lineEditOutputLength.setText(_translate("MainWindow", "0", None))
        self.lineEditInputArea.setText(_translate("MainWindow", "0", None))
        self.lineEditOutputMassFlow.setText(_translate("MainWindow", "0", None))
        self.lineEditInputDensity.setText(_translate("MainWindow", "0", None))
        self.lineEditOutputDensity.setText(_translate("MainWindow", "0", None))
        self.lineEditInputVolume.setText(_translate("MainWindow", "0", None))
        self.lineEditInputMass.setText(_translate("MainWindow", "0", None))
        self.labelTitleVelocity.setText(_translate("MainWindow", "Mass Flow", None))
        self.label_4.setText(_translate("MainWindow", "Density", None))
        self.labelTitleLength.setText(_translate("MainWindow", "Length", None))
        self.labelTitleArea.setText(_translate("MainWindow", "Area", None))
        self.lineEditOutputMass.setText(_translate("MainWindow", "0", None))
        self.lineEditInputLength.setText(_translate("MainWindow", "0", None))
        self.comboBoxFromLength.setItemText(0, _translate("MainWindow", "mm", None))
        self.comboBoxFromLength.setItemText(1, _translate("MainWindow", "cm", None))
        self.comboBoxFromLength.setItemText(2, _translate("MainWindow", "m", None))
        self.comboBoxFromLength.setItemText(3, _translate("MainWindow", "km", None))
        self.comboBoxFromLength.setItemText(4, _translate("MainWindow", "micron", None))
        self.comboBoxFromLength.setItemText(5, _translate("MainWindow", "inch", None))
        self.comboBoxFromLength.setItemText(6, _translate("MainWindow", "foot", None))
        self.comboBoxFromLength.setItemText(7, _translate("MainWindow", "mile", None))
        self.comboBoxToLength.setItemText(0, _translate("MainWindow", "mm", None))
        self.comboBoxToLength.setItemText(1, _translate("MainWindow", "cm", None))
        self.comboBoxToLength.setItemText(2, _translate("MainWindow", "m", None))
        self.comboBoxToLength.setItemText(3, _translate("MainWindow", "km", None))
        self.comboBoxToLength.setItemText(4, _translate("MainWindow", "micron", None))
        self.comboBoxToLength.setItemText(5, _translate("MainWindow", "inch", None))
        self.comboBoxToLength.setItemText(6, _translate("MainWindow", "foot", None))
        self.comboBoxToLength.setItemText(7, _translate("MainWindow", "mile", None))
        self.comboBoxFromArea.setItemText(0, _translate("MainWindow", "mm²", None))
        self.comboBoxFromArea.setItemText(1, _translate("MainWindow", "cm²", None))
        self.comboBoxFromArea.setItemText(2, _translate("MainWindow", "m²", None))
        self.comboBoxFromArea.setItemText(3, _translate("MainWindow", "km²", None))
        self.comboBoxFromArea.setItemText(4, _translate("MainWindow", "micron²", None))
        self.comboBoxFromArea.setItemText(5, _translate("MainWindow", "inch²", None))
        self.comboBoxFromArea.setItemText(6, _translate("MainWindow", "ft²", None))
        self.comboBoxFromArea.setItemText(7, _translate("MainWindow", "mile²", None))
        self.comboBoxToLength_2.setItemText(0, _translate("MainWindow", "mm²", None))
        self.comboBoxToLength_2.setItemText(1, _translate("MainWindow", "cm²", None))
        self.comboBoxToLength_2.setItemText(2, _translate("MainWindow", "m²", None))
        self.comboBoxToLength_2.setItemText(3, _translate("MainWindow", "micron²", None))
        self.comboBoxToLength_2.setItemText(4, _translate("MainWindow", "km²", None))
        self.comboBoxToLength_2.setItemText(5, _translate("MainWindow", "inch²", None))
        self.comboBoxToLength_2.setItemText(6, _translate("MainWindow", "ft²", None))
        self.comboBoxToLength_2.setItemText(7, _translate("MainWindow", "mile²", None))
        self.comboBoxFromVolume.setItemText(0, _translate("MainWindow", "mm³", None))
        self.comboBoxFromVolume.setItemText(1, _translate("MainWindow", "cm³", None))
        self.comboBoxFromVolume.setItemText(2, _translate("MainWindow", "m³", None))
        self.comboBoxFromVolume.setItemText(3, _translate("MainWindow", "micron³", None))
        self.comboBoxFromVolume.setItemText(4, _translate("MainWindow", "inch³", None))
        self.comboBoxFromVolume.setItemText(5, _translate("MainWindow", "ft³", None))
        self.comboBoxFromVolume.setItemText(6, _translate("MainWindow", "L", None))
        self.comboBoxToVolume.setItemText(0, _translate("MainWindow", "mm³", None))
        self.comboBoxToVolume.setItemText(1, _translate("MainWindow", "cm³", None))
        self.comboBoxToVolume.setItemText(2, _translate("MainWindow", "m³", None))
        self.comboBoxToVolume.setItemText(3, _translate("MainWindow", "micron³", None))
        self.comboBoxToVolume.setItemText(4, _translate("MainWindow", "inch³", None))
        self.comboBoxToVolume.setItemText(5, _translate("MainWindow", "ft³", None))
        self.comboBoxToVolume.setItemText(6, _translate("MainWindow", "L", None))
        self.comboBoxFromMass.setItemText(0, _translate("MainWindow", "kg", None))
        self.comboBoxFromMass.setItemText(1, _translate("MainWindow", "g", None))
        self.comboBoxFromMass.setItemText(2, _translate("MainWindow", "mg", None))
        self.comboBoxFromMass.setItemText(3, _translate("MainWindow", "tonne", None))
        self.comboBoxFromMass.setItemText(4, _translate("MainWindow", "lb", None))
        self.comboBoxFromMass.setItemText(5, _translate("MainWindow", "oz", None))
        self.comboBoxToMass.setItemText(0, _translate("MainWindow", "kg", None))
        self.comboBoxToMass.setItemText(1, _translate("MainWindow", "g", None))
        self.comboBoxToMass.setItemText(2, _translate("MainWindow", "mg", None))
        self.comboBoxToMass.setItemText(3, _translate("MainWindow", "tonne", None))
        self.comboBoxToMass.setItemText(4, _translate("MainWindow", "lb", None))
        self.comboBoxToMass.setItemText(5, _translate("MainWindow", "oz", None))
        self.comboBoxFromDensity.setItemText(0, _translate("MainWindow", "kg/m³", None))
        self.comboBoxFromDensity.setItemText(1, _translate("MainWindow", "g/m³", None))
        self.comboBoxFromDensity.setItemText(2, _translate("MainWindow", "mg/m³", None))
        self.comboBoxFromDensity.setItemText(3, _translate("MainWindow", "lb/ft³", None))
        self.comboBoxFromDensity.setItemText(4, _translate("MainWindow", "lb/in³", None))
        self.comboBoxFromDensity.setItemText(5, _translate("MainWindow", "oz//m³", None))
        self.comboBoxToDensity.setItemText(0, _translate("MainWindow", "kg/m³", None))
        self.comboBoxToDensity.setItemText(1, _translate("MainWindow", "g/m³", None))
        self.comboBoxToDensity.setItemText(2, _translate("MainWindow", "mg/m³", None))
        self.comboBoxToDensity.setItemText(3, _translate("MainWindow", "lb/ft³", None))
        self.comboBoxToDensity.setItemText(4, _translate("MainWindow", "lb/in³", None))
        self.comboBoxToDensity.setItemText(5, _translate("MainWindow", "oz/m³", None))
        self.comboBoxFromMassFlow.setItemText(0, _translate("MainWindow", "kg/s", None))
        self.comboBoxFromMassFlow.setItemText(1, _translate("MainWindow", "lb/hr", None))
        self.comboBoxFromMassFlow.setItemText(2, _translate("MainWindow", "kg/hr", None))
        self.comboBoxFromMassFlow.setItemText(3, _translate("MainWindow", "lb/min", None))
        self.comboBoxToMassFlow.setItemText(0, _translate("MainWindow", "kg/s", None))
        self.comboBoxToMassFlow.setItemText(1, _translate("MainWindow", "lb/hr", None))
        self.comboBoxToMassFlow.setItemText(2, _translate("MainWindow", "kg/hr", None))
        self.comboBoxToMassFlow.setItemText(3, _translate("MainWindow", "lb/min", None))
        self.btnConvert.setText(_translate("MainWindow", "Calculate", None))
        self.btnConversions.setTabText(self.btnConversions.indexOf(self.tabUnitConversion), _translate("MainWindow", "Conversions", None))
        self.labelCircleTitle.setText(_translate("MainWindow", "Calculate Circle Properties", None))
        self.labelInputCircle.setText(_translate("MainWindow", "Required inputs: any singe field.", None))
        self.labelDiameter.setText(_translate("MainWindow", "Diameter", None))
        self.txtCLS_Diamter.setText(_translate("MainWindow", "0", None))
        self.labelArea.setText(_translate("MainWindow", "Area", None))
        self.txtCLS_Area.setText(_translate("MainWindow", "0", None))
        self.labelCircumference.setText(_translate("MainWindow", "Circumference", None))
        self.txtCLS_Circumference.setText(_translate("MainWindow", "0", None))
        self.btnCircles.setText(_translate("MainWindow", "Calculate", None))
        self.btnConversions.setTabText(self.btnConversions.indexOf(self.tabCircles), _translate("MainWindow", "Circles", None))
        self.labelTaperTitle.setText(_translate("MainWindow", "Calculate Taper Properties", None))
        self.labelTaperInput.setText(_translate("MainWindow", "Required inputs: any 3 of 4 fields.", None))
        self.labelAngle.setText(_translate("MainWindow", "Taper Angle", None))
        self.labelDiameter1.setText(_translate("MainWindow", "Diameter 1", None))
        self.labelDiameter2.setText(_translate("MainWindow", "Diameter 2", None))
        self.labelLength.setText(_translate("MainWindow", "Length", None))
        self.txtTA_Angle.setText(_translate("MainWindow", "0", None))
        self.txtTA_Diameter1.setText(_translate("MainWindow", "0", None))
        self.txtTA_Diameter2.setText(_translate("MainWindow", "0", None))
        self.txtTA_Length.setText(_translate("MainWindow", "0", None))
        self.btnTaper.setText(_translate("MainWindow", "Calculate", None))
        self.btnConversions.setTabText(self.btnConversions.indexOf(self.tabTaper), _translate("MainWindow", "Taper", None))
        self.labelTitleRT.setText(_translate("MainWindow", "Calculate Racetrack Properties", None))
        self.labelInputRT.setText(_translate("MainWindow", "Required inputs: 2 of 4 inputs. Y is mandatory.", None))
        self.labelRTx.setText(_translate("MainWindow", "Racetrack X", None))
        self.labelRTy.setText(_translate("MainWindow", "Racetrack Y", None))
        self.labelRTarea.setText(_translate("MainWindow", "Area", None))
        self.labelRTcircumference.setText(_translate("MainWindow", "Circumference", None))
        self.txtRTRK_x.setText(_translate("MainWindow", "0", None))
        self.txtRTRK_csa.setText(_translate("MainWindow", "0", None))
        self.txtRTRK_cfm.setText(_translate("MainWindow", "0", None))
        self.txtRTRK_y.setText(_translate("MainWindow", "0", None))
        self.btnRacetrack.setText(_translate("MainWindow", "Calculate", None))
        self.btnConversions.setTabText(self.btnConversions.indexOf(self.tabRaceTrack), _translate("MainWindow", "Racetrack", None))
        self.labelTitleElipse.setText(_translate("MainWindow", "Calculate Elipse Properties", None))
        self.labelInputElipse.setText(_translate("MainWindow", "Required inputs: 2 of and 3 available inputs.", None))
        self.labelSMajor.setText(_translate("MainWindow", "Semimajor Dia", None))
        self.labelSMinor.setText(_translate("MainWindow", "Semiminor Dia", None))
        self.labelEArea.setText(_translate("MainWindow", "Area", None))
        self.labelEcircumference.setText(_translate("MainWindow", "Circumference", None))
        self.txtElipses_semimajor.setText(_translate("MainWindow", "0", None))
        self.txtElipses_semiminor.setText(_translate("MainWindow", "0", None))
        self.txtElipses_csa.setText(_translate("MainWindow", "0", None))
        self.txtElipses_circumference.setText(_translate("MainWindow", "0", None))
        self.btnElipses.setText(_translate("MainWindow", "Calculate", None))
        self.btnConversions.setTabText(self.btnConversions.indexOf(self.tabElipse), _translate("MainWindow", "Elipse", None))
        self.label_5.setText(_translate("MainWindow", "Calculate Rectangle Properties", None))
        self.label_6.setText(_translate("MainWindow", "Requires inputs for X and Y. R can be 0 or have a value.", None))
        self.label_10.setText(_translate("MainWindow", "Circumference", None))
        self.label_8.setText(_translate("MainWindow", "Y", None))
        self.label_9.setText(_translate("MainWindow", "R", None))
        self.label_7.setText(_translate("MainWindow", "X", None))
        self.txtRectangleR.setText(_translate("MainWindow", "0", None))
        self.txtRectangleCfm.setText(_translate("MainWindow", "0", None))
        self.txtRectangleY.setText(_translate("MainWindow", "0", None))
        self.txtRectangleX.setText(_translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "Area", None))
        self.txtRectangleArea.setText(_translate("MainWindow", "0", None))
        self.btnRectangle.setText(_translate("MainWindow", "Calculate", None))
        self.btnConversions.setTabText(self.btnConversions.indexOf(self.tab), _translate("MainWindow", "Rectangles", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuExit.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

